name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOTNET_NOLOGO: true
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - run: echo "::remove-matcher owner=csc::"
    - uses: reviewdog/action-setup@v1
    - run: dotnet --info
    - run: dotnet restore
    - run: dotnet build -c Release --no-restore | tee dotnet.buildlog
    - uses: SamhammerAG/dotnet-reviewdog-action@v1
      with:
        workdir: src
        reporter: github-check
        line_exclude_regex: ".*(warning|error) CS0618:.*"
    - run: dotnet test -c Release --no-build --logger "GitHubActions;report-warnings=false"
